spring.application.name=report-service

server.port=8085

spring.datasource.url=${REPORT_DB_URL:${DB_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/report_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago}}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

services.kpi-service.url=${KPI_SERVICE_URL:http://localhost:8084}

resilience4j.circuitbreaker.instances.kpiService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.kpiService.sliding-window-size=5
resilience4j.circuitbreaker.instances.kpiService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.kpiService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kpiService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.kpiService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.kpiService.automatic-transition-from-open-to-half-open-enabled=true

# Actuator - solo health para Docker healthcheck
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
